### ISSUE TITLE
docker not starting – nuveo/opencv missing?

### ISSUE THREAD

**Issue by Ambrosiani** [peterk/pimmer#2]
hi, this script came up again in a discussion. However I get the following error when trying to start the docker container:

`ERROR: Service 'worker' failed to build: pull access denied for nuveo/opencv, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Maybe opencv has moved? I'm not familiar enough with python to look for the current route, would love any help to get this up and running!

**Comment by peterk** [comment]
See https://github.com/nuveo/docker-opencv/issues/7. Will check for alternative
