### ISSUE TITLE
Add a small border for every image

### ISSUE THREAD

**Issue by EdoardoMantovani** [peterk/pimmer#4]
Hello again Peterk,

I  tested the tool on Linux and it works fine, the only "problem" is that I would like to cut the image from the current page a little bit "more" (like having a margin of 1cm), is it possible to implement it?

Thanks.

**Comment by peterk** [comment]
That would lead to text fragments and other things appearing in the detected image areas. If you want to add a border you should do this in post processing of the image files. 

If you want to revisit the page files to do the cut differently you will find a json file in the output directory. It contains coordinated for all detected objects in the "regions" property. You can use these as a starting point to do cuts differently.
